name: Release v1

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
  workflow_dispatch:
  push:
    branches:
      - v1.x

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release v1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm (v1)
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commitMode: "github-api"
        env:
          NPM_CONFIG_PROVENANCE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: otel-sdk-1
